sudo: false # cause Travis to start builds much faster
language: python
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  - git submodule update --init --recursive
install:
  - pip install -U setuptools
matrix:
  include:
    - os: linux
      python: "2.7"
      env:
        - SCRIPT=ci_lint.sh
    - os: linux
      python: "2.7"
      addons:
        apt:
          packages:
            - libnss3-tools
      env:
        - SCRIPT=ci_stability.sh
        - PRODUCT=firefox
    - os: linux
      python: "2.7"
      env:
        - SCRIPT=ci_stability.sh
        - PRODUCT=chrome
script:
  - bash $SCRIPT
notifications:
  email:
    on_success: never
    on_failure: always
